---
cgit_url: https://yhbt.net/kgio.git
ml_url:
- https://yhbt.net/kgio-public/
- http://ou63pmih66umazou.onion/kgio-public/
rdoc_url: https://yhbt.net/kgio/
public_email: kgio-public@yhbt.net
noindex:
- LATEST
- TODO
nntp_url:
- nntp://news.public-inbox.org/inbox.comp.lang.ruby.kgio
- nntp://ou63pmih66umazou.onion/inbox.comp.lang.ruby.kgio
source_code:
- git clone https://yhbt.net/kgio.git
- torsocks git clone http://ou63pmih66umazou.onion/kgio.git
